server:
  port: 8084
spring:
  application:
    name: 'coffee-orders-consumer'
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: coffee-orders-listener-group
      auto-offset-reset: latest
    properties:
      schema.registry.url : http://localhost:8081